name:  crypto-data-fetcher
on:
  push: 
    paths:
      - ".github/workflows/*"   # run workflow when any changes are commited to .github/workflows folder files
  schedule:
    - cron: '0 */12 * * *'      # runs every 12 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: crypto-data-fetcher
        run: echo "Cron job is working!!!"

      - name: checkout repo content
        uses: actions/checkout@v3   # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.7.*'
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: execute crypto-data-fetcher script
        run: python data-fetcher.py                                     # Updated file file to get more features   
      
      - name: commit files
        run: |                                                          # secrets added to repo
          git config --local user.email ${{ secrets.EMAIL_ADDRESS }}    
          git config --local user.name ${{ secrets.FULL_NAME }}
          git add -A
          git commit -m "update data" -a
      
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }} 